// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Applicants struct {
	UserID    string `json:"userId"`
	JobID     int32  `json:"job_id"`
	AppliedAt string `json:"applied_at"`
	Status    string `json:"status"`
	Resume    string `json:"resume"`
}

type ApplicationResponse struct {
	Response string `json:"response"`
	User     *User  `json:"user"`
}

type Approval struct {
	UserID int32 `json:"userId"`
	JobID  int32 `json:"job_id"`
}

type ApprovalResponse struct {
	Response string `json:"response"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type JobApplicantFilter struct {
	JobOfferID *int32  `json:"job_offer_id,omitempty"`
	UserID     *int32  `json:"user_id,omitempty"`
	Status     *string `json:"status,omitempty"`
}

type JobApplication struct {
	JobApplicationID int32          `json:"jobApplicationId"`
	JobID            int32          `json:"job_id"`
	UserID           int32          `json:"userId"`
	Proposal         string         `json:"proposal"`
	Cv               graphql.Upload `json:"cv"`
}

type JobFilter struct {
	JobOfferID *int32  `json:"job_offer_id,omitempty"`
	UserID     *int32  `json:"user_id,omitempty"`
	Category   *string `json:"category,omitempty"`
}

type JobOffer struct {
	JobID            string `json:"job_id"`
	JobType          string `json:"job_type"`
	Title            string `json:"title"`
	Description      string `json:"description"`
	Location         string `json:"location"`
	OfferedByuser    *User  `json:"offeredByuser"`
	Category         string `json:"category"`
	ApplicationCount int32  `json:"applicationCount"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Message struct {
	ID       string    `json:"id"`
	Message  string    `json:"message"`
	SenderID int32     `json:"senderId"`
	ChatID   string    `json:"chatID"`
	SentAt   time.Time `json:"sentAt"`
}

type Mutation struct {
}

type NewJobOffer struct {
	JobType          string `json:"job_type"`
	Title            string `json:"title"`
	Description      string `json:"description"`
	Location         string `json:"location"`
	OfferedByuser    int32  `json:"offeredByuser"`
	Category         string `json:"category"`
	ApplicationCount int32  `json:"applicationCount"`
}

type NewUser struct {
	ID          string `json:"id"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	PhoneNumber string `json:"phone_number"`
	Address     string `json:"address"`
	Role        string `json:"role"`
}

type Query struct {
}

type RejectionResponse struct {
	Response string `json:"response"`
}

type Subscription struct {
}

type User struct {
	ID          string  `json:"id"`
	FirstName   string  `json:"first_name"`
	LastName    string  `json:"last_name"`
	Email       string  `json:"email"`
	Password    string  `json:"password"`
	PhoneNumber string  `json:"phone_number"`
	Address     string  `json:"address"`
	Role        string  `json:"role"`
	Cv          *string `json:"cv,omitempty"`
	IsActive    bool    `json:"is_active"`
}
